"""Direct column-shape follow-up, no gameplay or saved map changes."""
import json
from pathlib import Path
import unreal as u
import optimize_collision

ROOT = Path('D:/devgames/MeridianSquad')
DEST = '/Game/ReinforcedColumn01/'
LOBBY = '/Game/Maps/L_OpeningLobby_PainterStone01'


def build(revision='06',evidence_root='Saved/ColumnShape04',preserve_steel=True):
    out = ROOT / evidence_root
    source = ROOT / 'Assets/Source/ReinforcedColumn01/ReinforcedColumn02-Candidate01'
    ed = u.get_editor_subsystem(u.UnrealEditorSubsystem)
    assert Path(u.Paths.convert_relative_path_to_full(u.Paths.project_dir())).resolve() == ROOT
    assert not ed.get_game_world()
    assert ed.get_editor_world().get_path_name() == LOBBY+'.L_OpeningLobby_PainterStone01'
    assert not u.EditorLoadingAndSavingUtils.get_dirty_map_packages()
    assert not u.EditorLoadingAndSavingUtils.get_dirty_content_packages()
    report = out / ('asset-build'+revision+'.json')
    assert not report.exists()
    u.EditorLoadingAndSavingUtils.new_blank_map(False)
    result = json.loads(u.NGDColumnAuthoring.build_column(str(source/('column'+revision+'.json'))))
    assert 'error' not in result, result
    (out/('automatic-collision'+revision+'.json')).write_text(json.dumps(result, indent=2))
    gc = u.load_asset(DEST+'GC_RC01_BondedConcrete')
    result = json.loads(u.NGDColumnAuthoring.apply_merged_collision(
        gc, str(source/('collision'+revision+'.json')), str(source/('design'+revision+'.json'))))
    report.write_text(json.dumps(result, indent=2))
    assert 'error' not in result, result
    assert result['geometries'] == 600 and result['anchored_count'] == 120
    assert not result['leaves_without_convex']
    assert result['convex_hulls'] <= 601 and result['convex_vertices'] <= 9442
    # BuildColumn also reimports identical steel. Reload its preserved package
    # instead of saving regenerated bytes; the source cage did not change.
    if preserve_steel:
        steel = u.load_asset(DEST+'SM_RC01_Rebar')
        u.EditorLoadingAndSavingUtils.reload_packages([steel.get_outer()],
            u.ReloadPackagesInteractionMode.ASSUME_POSITIVE)
    optimize_collision.build(out/('core-collision'+revision+'.json'))
    allowed = {DEST+n for n in ['GC_RC01_BondedConcrete', 'SM_RC01_SupportedColumn',
        'SM_RC01_CoreCollision', 'SM_RC02_Preview_Shallow', 'SM_RC02_Preview_Deep']}
    if not preserve_steel:
        allowed.add(DEST+'SM_RC01_Rebar')
    dirty = u.EditorLoadingAndSavingUtils.get_dirty_content_packages()
    assert all(p.get_path_name() in allowed for p in dirty), [p.get_path_name() for p in dirty]
    for path in sorted(allowed):
        assert u.EditorAssetLibrary.save_asset(path, only_if_is_dirty=True)
    print(json.dumps(dict(revision=revision, geometries=result['geometries'],
        hulls=result['convex_hulls'], vertices=result['convex_vertices'])))
