int main(){
    int Checks=0;auto Check=[&](bool Pass,const char* Name){++Checks;if(!Pass){std::cerr<<Name<<'\n';std::exit(1);}};
    UEnemyCombatComponent E;ACharacter Defaults,Source;Source.Defaults=&Defaults;E.Fixture.Foundation=&Source;
    Source.Capsule.Radius=Defaults.Capsule.Radius=SourceRadius;
    Source.Capsule.HalfHeight=Defaults.Capsule.HalfHeight=SourceStanding;Source.CMC.CrouchedHalfHeight=SourceCrouch;
    float R=0,H=0;Check(!Source.HasMover,"fixture uses CMC with no Mover adapter");
    Check(E.PoseCapsuleSize(false,R,H)&&R==50&&H==86,"actual source standing proposal");
    Check(E.PoseCapsuleSize(true,R,H)&&R==50&&H==60,"actual source crouched proposal");
    Source.Capsule.HalfHeight=60;
    Check(E.PoseCapsuleSize(false,R,H)&&H==86,"standing proposal while achieved crouched uses class default");
    E.CapsuleSize(R,H);Check(H==60,"achieved capsule read remains crouched");
    Source.Capsule.Scale={2,2,2};Check(E.PoseCapsuleSize(false,R,H)&&R==100&&H==172,"current scale applies to default standing dimensions");
    Check(E.PoseCapsuleSize(true,R,H)&&R==100&&H==120,"scaled crouch proposal");
    Source.Capsule.Scale={1,2,1.5};Check(E.PoseCapsuleSize(false,R,H)&&R==50&&H==129,"UE5.8 nonuniform XY radius and Z height rule");
    Source.CMC.CrouchedHalfHeight=20;Check(E.PoseCapsuleSize(true,R,H)&&R==50&&H==75,"crouch height clamps to radius before scale");
    Source.Capsule.Scale={1,1,1};Source.Capsule.Radius=55;
    Check(E.PoseCapsuleSize(false,R,H)&&R==50,"uncrouch restores default radius");
    Check(E.PoseCapsuleSize(true,R,H)&&R==55&&H==55,"crouch retains current radius");
    Source.Capsule.Radius=50;Source.CMC.CrouchedHalfHeight=60;
    FVector Ground;CombatAI::PositionRejection Why;
    Check(E.TacticalGround({0,0,0},Ground,Why,0)&&E.World.Overlaps>0&&E.World.LastHeight==86,"mobile standing producer reaches real overlap consumer");
    Check(E.TacticalWalk({0,0,0},{100,0,0},0)&&E.World.Sweeps>0&&E.World.LastHeight==86,"mobile standing route reaches real sweep consumer");
    Check(E.CoverCapsule({0,0,0},false)&&E.World.LastHeight==86,"standing lean-cover proposal reaches clearance");
    Check(E.CoverCapsule({0,0,0},true)&&E.World.LastHeight==60,"low-cover crouch proposal reaches clearance");
    Check(E.CoverWalk({0,0,0},{100,0,0})&&E.World.LastHeight==60,"cover travel reaches crouched route sweep");
    E.World.Block=true;
    Check(!E.CoverCapsule({0,0,0},false)&&!E.TacticalWalk({0,0,0},{100,0,0},0),"blocking clearance still rejects proposals");
    E.World.Block=false;E.World.Floor=false;Check(!E.CoverCapsule({0,0,0},true),"unsupported floor still rejects");E.World.Floor=true;
    Source.HasCMC=false;Check(!E.PoseCapsuleSize(false,R,H),"missing CMC fails closed");Source.HasCMC=true;
    Source.Defaults=nullptr;Check(!E.PoseCapsuleSize(false,R,H),"missing standing default fails closed");Source.Defaults=&Defaults;
    Source.Capsule.Scale={0,1,1};Check(!E.PoseCapsuleSize(true,R,H),"zero scale fails closed");
    Source.Capsule.Scale={-1,1,1};Check(!E.PoseCapsuleSize(true,R,H),"negative scale fails closed");
    Source.Capsule.Scale={2,2,.5};Check(!E.PoseCapsuleSize(true,R,H),"invalid scaled height/radius envelope fails closed");
    Source.Capsule.Scale={1,1,1};Source.CMC.CrouchedHalfHeight=std::numeric_limits<float>::quiet_NaN();
    Check(!E.PoseCapsuleSize(true,R,H),"nonfinite stance setting fails closed");
    E.Fixture.Foundation=&E.Fixture.Data;
    Check(E.PoseCapsuleSize(true,R,H)&&H==55,"historical Mover branch remains available");
    E.Fixture.Data.HasMover=false;Check(!E.PoseCapsuleSize(true,R,H),"unsupported movement stack fails closed");
    std::cout<<Checks<<" extracted production geometry/clearance assertions passed\n";
}
